### ISSUE TITLE
GraphQL: using value from BatchLoader in another field

### ISSUE THREAD

**Issue by holic** [exAspArk/batch-loader#42]
I have something that looks like this:

```rb
class Group < GraphQL::Schema::Object
  field :members, [String], null: false
  field :members_count, Int, null: false

  def members
    BatchLoader::GraphQL.for(object.id).batch(default_value: []) do |ids, loader|
      # query for all member associations for group IDs
    end
  end

  def members_count
    members.count
  end
end
```

But `members_count` reading from `members` throws an error like

```
undefined method `count' for #<BatchLoader::GraphQL:0x000...>
```

This was working before the 1.3.0 changes.

**Comment by exAspArk** [comment]
Hi @holic,

Yes, with the latest version you'd need to use `members.sync.count` if you'd like to resolve it manually.

However, you probably have this issue because it shouldn't be used that way :) I'll try to explain. Imagine you have the following query:


```
{
  groups {
    membersCount # <= N+1
    members      # returns BatchLoader::GraphQL
  }
}
```

Because `membersCount` doesn't return a lazy `BatchLoader::GraphQL` object, GraphQL Ruby gem doesn't know whether it should resolve the field lazily after collecting information about all groups. That is why there might be cases when GraphQL Ruby gem will be executing `members_count` for each `group`, resolving `BatchLoader` from `members` earlier and producing N+1 queries.

You might want to return `BatchLoader::GraphQL` from `members_count` as well.

**Comment by holic** [comment]
Thanks for the quick reply! That makes sense.

I tried that snippet, but still getting the `undefined method` error. I also tried a slight variation:
```rb
def members_count
  BatchLoader::GraphQL.for(object.id).batch { |_, loader| loader.call(object.id, members.sync.size) }
end
```
(Note the `sync` call)

If I understand correctly, I think this is still failing because once we drop into the batch block, we've lost the context of the individual record we're inside of (a `Group`, in this case)?

**Comment by exAspArk** [comment]
Hey @holic,

Sorry, my bad. The example won't work since the second batch will be executed within the context of just one of the groups, not all of them:

```rb
def members_count
  BatchLoader::GraphQL.for(object.id).batch do |_, loader|
    # members <= 1 of N groups within the current Group, we need to get all of them
    loader.call(object.id, members.sync.size)
  end
end
```

There are multiple ways of making it work. One of them is to cache members request and reuse it. For example:

```rb
def members
  BatchLoader::GraphQL.for(object.id)....
    fetch_members(ids)... # with members
  end
end

def members_count
  BatchLoader::GraphQL.for(object.id)....
    fetch_members(ids)... # with members.count
  end
end

private

def fetch_members(ids)
  # cache association per ids from params, e.g.
  @members ||= Hash.new { |h, key| h[ids] = ...where(id: ids) }
  @members[ids]
end
```

Since BatchLoader already has an implemented caching (per thread, not just an instance variable), we could add some functionality:

```rb
def fetch_members(ids)
  BatchLoader.for(ids).cache { ...where(id: ids) }
end
```
